BOARD_TAG = leonardo
ARDUINO_PORT                                                                                                 = /dev/ttyACM0
ARDUINO_LIBS = Tah_Arduino_Library Servo
ARDUINO_DIR = /usr/share/arduino
include /home/pi/Tah_Testbed/Arduino/Arduino.mk


