BOARD_TAG = leonardo
ARDUINO_PORT                                                                                                 = /dev/ttyACM0
ARDUINO_LIBS =
ARDUINO_DIR = /usr/share/arduino
include /home/pi/GitRepo/Arduino-Makefile/Arduino.mk

